In [22]:
'''
author @ nicole diaz flores
date:02/01/2021
prof: Jonathan Lee
class: Data Modeling BSSD3850
'''

#--------------------------------------- IMPORTS
import numpy as np


#---------------------------------------- GLOBAL VAR.
matrix_a = ([3,-1,2],[-2,4,0])
matrix_b = ([2,0],[-1,4],[-3,2])

#print(matrix_a)
#print()
#print(matrix_b)



#--------------------------------------- QUESTION 4
def q4():
    res = np.dot(matrix_a,matrix_b)
    print(res)

In [23]:
#---------------------------------------- QUESTION 7
def q7():
    res = np.dot(matrix_b,matrix_a)
    print(res)

In [27]:
#---------------------------------------- QUESTION 12
def q12():
    mata = ([3,-2,5],[0,-1,6],[-4,2,-1])
    matb = ([2,-1,0],[3,-5,2],[1,4,-2])
    
    res = np.dot(matb,mata)
    print(res)

In [29]:
#-------------------------------- Main()

#QUESTION 4: Correct answer on code & website
print("Q4:")
q4()
print("\n------------------------------------------")

#QUESTION 7: Correct answer on code & website
print("Q7:")
q7()
print("\n------------------------------------------")

#QUESTION 12: Correct answer on code & website
print("Q12: ")
q12()

Q4:
[[ 1  0]
 [-8 16]]

------------------------------------------
Q7:
[[  6  -2   4]
 [-11  17  -2]
 [-13  11  -6]]

------------------------------------------
Q12: 
[[  6  -3   4]
 [  1   3 -17]
 [ 11 -10  31]]
